import type { Metadata } from "next";
import TopNavbar from "@/components/top-nav-bar";
import AsideSidebar from "@/components/aside-sidebar";
import Script from "next/script";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
export default function AdminRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <TopNavbar />
      <AsideSidebar />
      <div className="p-4 mt-16 sm:ml-72">
        <div className="p-4 border-2 border-gray-200 border-dashed rounded-lg">
          {children}
        </div>
      </div>
      <Script  src="/script.js"></Script>
    </>
  );
}
